### ISSUE TITLE
Support MSA311

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_MSA301#17]
MSA311 is very similar, but has address `0x62` instead of `0x26`. The current MSA301 consturctor does not allow passing in an alternate I2C address.

@ladyada @kattni should we rename this library to MSA3x1 and/or provide an optional I2C address arg? You are familiar with other sensor families that also vary very little between different part numbers.

**Comment by bradanlane** [comment]
If it doesn't quake too many users, I am in favor of making the library name cover both MPUs and adding the I2C address parameter.

_(currently, I've just been using a forked copy with the required changes to support the MSA311)_

**Comment by dhalbert** [comment]
@bradanlane We would welcome a PR and will rename the library appropriately. Thanks!

**Comment by dhalbert** [comment]
or @WhiteMatrix, who has forked this.

**Comment by caternuson** [comment]
My two cents - I like the subclass approach in the @WhiteMatrix fork, since each variant has only one I2C address. I'd also suggest moving these lines from `__init__` into a new function in the base class that gets called from `__init__`. Just a code dupe thing.

```python
        self._disable_x = self._disable_y = self._disable_z = False
        self.power_mode = Mode.NORMAL
        self.data_rate = DataRate.RATE_500_HZ
        self.bandwidth = BandWidth.WIDTH_250_HZ
        self.range = Range.RANGE_4_G
        self.resolution = Resolution.RESOLUTION_14_BIT
        self._tap_count = 0
```

**Comment by WhiteMatrix** [comment]
Hello,
the subclass idea is taken from [AdafruitSensor library](https://adafruit.github.io/Adafruit_MSA301/html/class_adafruit___m_s_a311.html). But I don't know if that's the correct way in CircuitPython, more common thing I see is an extra `address` parameter in the constructor.
I can extract the `__init__` function and make a pull request here. But I should I update everything else to say 
`Adafruit_MSA3x1`, like the library file itself and the docs? I rarely do open-source. Should the authors header be updated?
Also, the sensor isn't exactly the same, in the acceleration ranges the sensitivity differs between two ICs, there are some differences in the register map, but just by using the existing code the readings seem correct and tap detection works, but I don't have a MSA301 to compare.

**Comment by tekktrik** [comment]
@caternuson is this completed via #18?

**Comment by caternuson** [comment]
Hopefully :)
